dist: trusty
sudo: required
language: bash
before_install:
# packer validate
# terraform validate
# tflint
# ansible-lint
# otus tests
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-08/run.sh | bash
notifications:
  slack:
    rooms:
      secure: Cao6ZcyE64I8bLpSj2KfNlpIsZmYFeh0xiaKR6Qa2B7O6fIIXCnhQicwtIk7sFRJJ23Tz2d+UrDD6zF71osJxpFUh7po7P2ehniidlElk6+Sn9BMN41E9yvOLcaqEtxzLxFJRf2zjUc0oR71BQlVJK2t0WjuHlxVgvRhHAw2c/gc5zw2XNuoYc7M0ODiu3clAJviNsCjylNsCfI9gDytHoCSYKxuwkIaElgoEz9rkS42PcNg/XdsmhHGYDh39Ab1jAsVIMNbjbVQor6YnDLPKP3/2uOd3unGO9SHrayu7YbYr/ex1UhH/q7vmVS6hMpxH+74QrCp2P6SV6zhuoUBqlCdh6ytsKra7D26P968duCovsTU3NlNSbSJlfl4kuvPGSYq8BoiXYw7IrkAtUTSuSugUzoTK2vKV4Ej6iRCllWVX5DKWDFfrKXgp+OR6V1drualFA3wE66nbtSBdzwRbTfcyhiPK6X3/PIw53f5JKRzowvDlJhvVhEWbEo+9BtfwGaCrTrsik/P3NGUBtsDbf4WZksHU+D+BZXc1eY2zrQvmzZXh5Ez4h1asUvudsXeraVPI5reE11MybmsoqXTbYj+P20lTkDYKEICZAFM9wM8QG1MfrLTNNwEiPEKG4VxPe1/7qisprQc3M0NoZroYQYp50yE2wnFU4q9KamvrXo=
