dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-08/run.sh |
  bash
notifications:
  slack:
    secure: bhNc4HHZJx3gdHbaxfiBmMiQUs+rotlI7jY+QPpliKTETqEzBfW8QxmBaJM4+ZIpFpncx1l2El5AXfBnQB6s1qItDg7mimd7oFNv255pL1KsDcYpVYP+rzVsou22y4c9c5EgHjcL5cxYJyMRsBpJX4WR2V6iuqb9s4oG137HxcPGMPkbR1x62m+enti/L5dNh6VE/SoS8Pxu0VLOrBc0f0fYXgnGQkbsUsCjivvMGlWhVDaXm6D/zOnjl+C6Jh9bM7WTD8DooEQRGV8AYWXskxiblfQAv1J9FbJKap61tewW6owPHVjqkRshUBeR3OAw8NeByK5pfk2WJzPHNbRy5AwIP6xBBWsgSiClV/FnE+asODrrS7uzAek4Bi0AMrzKuXdCts4Koc04rc3s+i+5+q1IAKVJID2WsX0cpA967vp9VoxBA1l5tGNHHZT4DcYskv4Zn7rvNz3TmXcVW7XSlq4zNdTjpNWyfCZoFs8nsZEfYZYezDrNHO+1oKRPomFMfcTE4J2zJZesEzEVJNvKhiE1z1/SPplf0MG2ZRfUMvEMZXEk2wrmgZK3eG89hqhWfOmqYiQNICgi5cZCrtgAC4155gBnvtsv9C3OcYJYFOlz9JuwAqDCEz+IhBCg4LSdj1AGXgVqKQHq2M16hPE4wcgTyulZwKqnW6iGbUM2F/g=
